### ISSUE TITLE
Fast exit

### ISSUE THREAD

**Issue by opclient** [DeBos99/ytviewer#1]
When I starting view bot it ends for 1 sec.

**Comment by DeBos99** [comment]
Hello @opclient 
Tell me how you are starting the bot (command in terminal) and what output you are getting in terminal.

**Comment by opclient** [comment]
Bot just starting. 1-2 sec and console closed.

**Comment by DeBos99** [comment]
Ok, bot starting, but how you are running it?
For now, bot can't be run without command line arguments.

**Comment by opclient** [comment]
![screenshot_15](https://user-images.githubusercontent.com/30980283/53694915-87682580-3de7-11e9-9044-6d3b6f47449d.png)

**Comment by DeBos99** [comment]
I added little error handling to the script, so when you will clone the repository again and you will run the bot, you should get error message and I will be able to fix that.
Please send me any error messages as soon as possible.

**Comment by opclient** [comment]
![screenshot_16](https://user-images.githubusercontent.com/30980283/53695211-ff841a80-3dea-11e9-8c79-56728eeffc33.png)
something with chromedriver

**Comment by DeBos99** [comment]
Ok, you need to download chromedriver from here http://chromedriver.chromium.org/downloads and you need to put the executable to folder in your PATH (it can be C:\Windows)

**Comment by opclient** [comment]
![image](https://user-images.githubusercontent.com/30980283/53695332-a87f4500-3dec-11e9-8861-5036a0c7da67.png)

**Comment by DeBos99** [comment]
Installing Google Chrome browser should help.
https://www.google.com/chrome/

I'm planning to add support for Firefox.

**Comment by opclient** [comment]
Thx. Working.

**Comment by DeBos99** [comment]
Your welcome. I'm glad it works.
