### ISSUE TITLE
Proxies not work for me.

### ISSUE THREAD

**Issue by edison1105** [DeBos99/ytviewer#11]
got ERR_CONNECTION_RESET

**Comment by DeBos99** [comment]
I need more informations. Tell me the command that you are running.

**Comment by fortniteil** [comment]
hello what proxies needed for this?

btw i got this error
[12940:13176:0513/044248.624:ERROR:wmi_refresher.cc(137)] Unable to add the Win32_PerfRawData_PerfDisk_PhysicalDisk enum

**Comment by DeBos99** [comment]
You don't need your own proxies. You can ignore `--proxies` option and bot will download list of proxies from the website.
Same as above, I need more informations about your issue. What OS are you using, what command? Screenshot of terminal with error would be best.

**Comment by fortniteil** [comment]
hello, i have fixed it, it was a problem with the chromedriver, the script is really good is got me like 100 viewers on youtube livestream :)

**Comment by DeBos99** [comment]
I'm glad you like the bot and that you fixed the problem.
