### ISSUE TITLE
Git bash

### ISSUE THREAD

**Issue by KingThoew** [DeBos99/ytviewer#12]
In git bash when im doing cd ytviewer and come to the master directory and do
install.bat

bash: install.bat: command not found 

??

i have set the path to geckodriver in PATH variables aswell

**Comment by KingThoew** [comment]
ps. forgot to mention that i do use windows 10

**Comment by DeBos99** [comment]
Please tell me the output of:
```
pwd
ls -l
```

**Comment by KingThoew** [comment]
$ ls -l
total 26
-rw-r--r-- 1 denni 197609  108 maj 12 19:41 install.bat
-rwxr-xr-x 1 denni 197609 2788 maj 12 19:41 install.sh*
-rw-r--r-- 1 denni 197609 1097 maj 12 19:41 LICENSE
-rw-r--r-- 1 denni 197609 4239 maj 12 19:41 main.py
-rw-r--r-- 1 denni 197609 2578 maj 12 19:41 README.md
-rw-r--r-- 1 denni 197609   44 maj 12 19:41 requirements.txt
drwxr-xr-x 1 denni 197609    0 maj 12 19:46 ytviewer/

**Comment by DeBos99** [comment]
Try running `sudo ./install.sh`

**Comment by KingThoew** [comment]
bash: sudo: command not found

**Comment by DeBos99** [comment]
Ok, so please open git bash as an administrator and in ytviewer directory run `./install.sh`

**Comment by KingThoew** [comment]
denni@LAPTOP-7526OMBT MINGW64 ~/ytviewer (master)
$ ./install sh
bash: ./install: No such file or directory

**Comment by KingThoew** [comment]
But when i did the ./install.bat command this happened:

denni@LAPTOP-7526OMBT MINGW64 ~/ytviewer (master)
$ ./install.bat

C:\Users\denni\ytviewer>title YTViewer installer

C:\Users\denni\ytviewer>color 0a

C:\Users\denni\ytviewer>pip install -r requirements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\denni\ytviewer>echo Successfully installed YTViewer.
Successfully installed YTViewer.

**Comment by DeBos99** [comment]
Its `./install.sh`, not `./install sh` (there is dot in first one).

**Comment by KingThoew** [comment]
$ ./install.sh
This script must be run as root.

**Comment by DeBos99** [comment]
Did you run git bash as an administrator?

**Comment by KingThoew** [comment]
Yes i did.

**Comment by KingThoew** [comment]
If you need to reach me faster, you can do so on discord:

Ken#4867

**Comment by DeBos99** [comment]
I can't add you. You can add me: DeBos#3292

**Comment by KingThoew** [comment]
Added you!
