### ISSUE TITLE
please help[ sir 

### ISSUE THREAD

**Issue by ayeshakhan2118** [DeBos99/ytviewer#13]
firefox
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    update_proxies()
  File "main.py", line 37, in update_proxies
    proxies=queue.deque(proxies)
AttributeError: 'module' object has no attribute 'deque'

**Comment by DeBos99** [comment]
Tell me what version of Python are you using.
You can get this by executing following command: `python --version`

**Comment by DeBos99** [comment]
I made little fix for `queue` module, so try cloning repository again and tell me if problem persists.
