### ISSUE TITLE
sir help again plz 

### ISSUE THREAD

**Issue by ayeshakhan2118** [DeBos99/ytviewer#14]
ytviewer/ytviewer# python main.py -u https://www.youtube.com/watch?v=5D9Ri_9EoSE -d 10 -dr firefox
100 proxies successfully loaded!
181.129.183.19:53281
Traceback (most recent call last):
  File "main.py", line 58, in bot
    options.headless=args.headless
AttributeError: can't set attribute

**Comment by DeBos99** [comment]
Tell me if issue #13 is sorted out.
