### ISSUE TITLE
[BUG] Views are not updating

### ISSUE THREAD

**Issue by ak0der1** [DeBos99/ytviewer#18]
**Description**
Views are not counted on YouTube.

**Command**
`python main.py --url https://www.youtube.com/watch?v=5WGAJzQdYRM --threads 1 --proxies *path*`

**Logs**

**Software**
OS: Mac
Python version: 3.7.3
WebDriver: chrome

**Comment by DeBos99** [comment]
Please check YouTube Analytics and tell me if views are updated here.

**Comment by ak0der1** [comment]
Yes, I am checking there. They are not updating.

**Comment by DeBos99** [comment]
When you run the bot look at the webdriver window and tell me if video is played automatically.

**Comment by ak0der1** [comment]
yes, everything seems perfect. I even paused video, to check, if IP is changed or not, IP is also getting changed.

**Comment by DeBos99** [comment]
Add `--user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5"` to the command. If it doesn't help try using default proxies (remove `--proxies` option) and let me know if that helps.

**Comment by ak0der1** [comment]
in mac 
main.py: error: unrecognized arguments: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5

I tried in windows. views still didn't count

I tried removing my proxies as well.

Nothing new.

**Comment by DeBos99** [comment]
I will have to take closer look at the issue. I will let you know if I will find something.

**Comment by ak0der1** [comment]
Thank you, may be they traced my mac address?

**Comment by DeBos99** [comment]
Its not possible. I'm assuming that something is wrong with your video or there was some security update on YouTube.

**Comment by ak0der1** [comment]
ok, I will test on more video's let's see.

**Comment by DeBos99** [comment]
Can you tell me did the bot worked before because I see that you used the bot on the video.

**Comment by ak0der1** [comment]
It delivered few views, may be 20-30.

**Comment by ak0der1** [comment]
I told my friends, to watch the video, to see, If youtube blocked or something. when they opened video. The count also increased in analytics.

**Comment by DeBos99** [comment]
Are your friends using same OS as you?
Are they using chrome browser?

**Comment by ak0der1** [comment]
yes. some mac and some windows but not on my internet connection.

**Comment by DeBos99** [comment]
Probably it only counted only these using windows.

**Comment by ak0der1** [comment]
I tried, running this code in windows as well. Didn't work for me.

**Comment by DeBos99** [comment]
Did you try on other, not already 'botted' videos?

**Comment by ak0der1** [comment]
I just tried new video , only 1st view got counted. its 10th new window opened. No change in analytics

**Comment by DeBos99** [comment]
I will take closer look at this issue this week.

**Comment by ak0der1** [comment]
I think, we need to find a way to spoof device - I tried changing ip and user agent manually - it didn't work. They can track our device info.

**Comment by DeBos99** [comment]
Try updating bot and tell me if issue still persists.
Don't add your own proxies for now if you have them.

**Comment by ak0der1** [comment]
Hey, I tried, using with and without using proxies, on mac and on windows as well. 
Nothing changed.

**Comment by DeBos99** [comment]
I have been informed that there is problem with proxies and for now only geckodriver (firefox) is changing IP address. Please try using geckodriver by adding `--driver firefox` to the command and let me know if problem is fixed.

**Comment by ak0der1** [comment]
Hey, Something strange is happening here, Please confirm. is it same with everyone.
Views are not updating live. 
I left bot running for approx. 1 hour.
Now after 2 hours they started updating- at the old time's place.

**Comment by DeBos99** [comment]
So more less views are updating? Everytime the video is watched correctly by bot, you should get information in terminal.

**Comment by ak0der1** [comment]
Yes, and They are now updated on live side as well. :)

**Comment by DeBos99** [comment]
No problem. I'm glad everything works.
