### ISSUE TITLE
[FEATURE] Add possibility to define txt files with videos

### ISSUE THREAD

**Issue by pimboli** [DeBos99/ytviewer#20]
**Description**
Hi, 
would be great if we could define a txt file (ex --playlist) which may include multiple video files, like this the tool could be used for multiple videos at the same time.

On top it would be great to have the possibility to define how many times a specivic video shall be played and the duration.

Ex. myvideos.txt:

URL;NrofPlaypacks;minSEC;maxSEC
https://www.youtube.com/watch?v=6pAIWh8bbVQ;100;10;25
https://www.youtube.com/watch?v=6pAIWhasdasd;5000;100;150

In the first example the video would be played 100 times with random playback time between 10 and 25 seconds.

Ps. repect, I like your project!

**Requirements**
Clearly describe what requirements your feature has if any.

**Code**
You can include valid python code or pseudocode if you want to help me in adding your feature.

**Comment by DeBos99** [comment]
There is option to add list of videos.
See: https://github.com/DeBos99/ytviewer#required-arguments
E.g. `python main.py --url file`
There is also `--duration` argument which sets for how many seconds the video should be viewed.
Only thing that is not implemented is random duration between min and max.
It will be added this or next week.
