### ISSUE TITLE
[BUG] Problems with external proxy list

### ISSUE THREAD

**Issue by pimboli** [DeBos99/ytviewer#21]
**Description**
Hi,

adding -p proxy.txt to to the command with the following proxies inside the proxy.txt:

62.210.45.29:1026
62.210.45.29:1027
62.210.45.29:1028
62.210.45.29:1029

results into problems.

a) firefox as driver:
`Traceback (most recent call last):
  File "main.py", line 64, in bot
    firefox_profile.set_preference('network.proxy.http_port',proxy.split(':')[1])
IndexError: list index out of range
`
b) chrome as driver:
Chrome instance starts but as soon as the 2nd instance opens the first crashes (without error in terminal)

Is the format of my proxylist wrong?

Thanks in advance.
**Command**
Executed command.

**Logs**
Logs of executed command.

**Software**
OS: Macos & Linux
Python version: python 3
WebDriver: chrome and ff

**Comment by DeBos99** [comment]
I need full terminal output.

**Comment by pimboli** [comment]
Chrome:
python3 main.py -dr chrome -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
5 proxies successfully loaded!

62.210.85.29:1044
62.210.85.29:1043
62.210.85.29:1042
139.162.25.246:3128
-------------------------
FF:
python3 main.py -dr firefox -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
5 proxies successfully loaded!

Traceback (most recent call last):
  File "main.py", line 64, in bot
    firefox_profile.set_preference('network.proxy.http_port',proxy.split(':')[1])
IndexError: list index out of range

**Comment by DeBos99** [comment]
Ok, I see what is the problem. Will be fixed today.

**Comment by DeBos99** [comment]
I updated the bot, check now and tell me if problem still persists.

**Comment by pimboli** [comment]
yes, still exists for chrome:

chrome:
`python3 main.py -dr chrome -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
[INFO][0] 25 proxies successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1050
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
[INFO][1] Successully started webdriver!
[INFO][2] Connecting to 62.210.85.29:1049
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.62 Safari/537.36
[INFO][1] Video successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1048
[INFO][1] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36
[INFO][2] Successully started webdriver!
[INFO][1] Successully started webdriver!
[INFO][2] Video successfully loaded!
[INFO][2] Connecting to 62.210.85.29:1047
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36
[INFO][1] Video successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1046
[INFO][1] Setting user agent to Mozilla/5.0 (X11; OpenBSD amd64; rv:28.0) Gecko/20100101 Firefox/28.0
[INFO][2] Successully started webdriver!
[INFO][1] Successully started webdriver!
[INFO][2] Video successfully loaded!
[INFO][2] Connecting to 62.210.85.29:1045
[INFO][2] Setting user agent to Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
[INFO][1] Video successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1044
[INFO][1] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1664.3 Safari/537.36
[INFO][2] Successully started webdriver!
[INFO][1] Successully started webdriver!
[INFO][2] Video successfully loaded!
[INFO][2] Connecting to 62.210.85.29:1043
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1500.55 Safari/537.36
`
Firefox: 
opens the multiples instances, but doesn't use the proxy,
when I replace manully the url in FF with whatismyip.com, it shows me my own public ip.
`python3 main.py -dr firefox -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
[INFO][0] 25 proxies successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1050
[INFO][1] Setting user agent to Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36
[INFO][2] Connecting to 62.210.85.29:1049
[INFO][2] Setting user agent to Mozilla/5.0 (X11; Linux i686; rv:64.0) Gecko/20100101 Firefox/64.0
[INFO][1] Successully started webdriver!
[INFO][1] Video successfully loaded!
[INFO][2] Successully started webdriver!
[INFO][2] Video successfully loaded!`
(btw: I also noticed now that FF does not autostart the video, but also without the -p parameter)

Here a screencast:
https://send.firefox.com/download/69f15e90e64ebca4/#UrG47OVEKFgetE8WzRdI_A

Thanks!

**Comment by DeBos99** [comment]
Firstly, your proxies not working, because bot closes the window. Make sure that your proxies support https.
Secondly, I have to fix error handling in the bot, then I will be able to get error message about driver itself.
I will let you know when I will update the bot.

**Comment by pimboli** [comment]
Hi, 
my proxies are working but are IP blocked.

```
curl -x, --proxy 62.210.85.29:1044  https://ifconfig.co
78.190.130.35
```
I tried befor already with a public proxy list, same result.
https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt

**Comment by DeBos99** [comment]
Firstly, I will not give you my IP address.
Secondly, please remove `--proxies` option from your command and tell me if result is still the same.

**Comment by pimboli** [comment]
Without the proxy parameter:

Chrome:
works fine, opens instances + public proxies are working.

Firefox:
problem, opens instances + public proxies are NOT working

It seems that firefox always ignores the proxies.

https://send.firefox.com/download/b9da3591eb70c8f0/#G-5n6xNdi4nbgOwOkUR76Q

**Comment by DeBos99** [comment]
I looks like it ignores everything passed through firefox profile. For now you have to use chromedriver.

**Comment by pimboli** [comment]
I also found out that YouTube seems to detect the accesses from the public proxies and doesn't count those hits.

I tested with my private proxies manually by launching chrome instance and those hits are counted.

**Comment by DeBos99** [comment]
I fixed some issues with the bot.
Could you update it and tell me if issue still persists?

**Comment by aidaninman3** [comment]
Im getting an error on line 84 saying Fakeuseragenterror maximum amount of retries reached

**Comment by DeBos99** [comment]
Please provide screenshot.

**Comment by pimboli** [comment]
Hi,

Firefox:
starts without problem but is not applying the proxy settings correctly.
I did some debugging. Check my screenshots:
https://imgur.com/a/3WHu6wm
The proxy server address is set correctly but the port isn't set, thats the reason why FF ignores proxy and uses own public IP.
This is the case for both scenarios with and without -p parameter

`main.py -dr firefox -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
[INFO][0] 25 proxies successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1050
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:23.0) Gecko/20131011 Firefox/23.0
62.210.85.29
1050
[INFO][2] Connecting to 62.210.85.29:1049
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36
62.210.85.29
1049
[INFO][1] Successully started webdriver!
[INFO][1] Video successfully loaded!
[INFO][2] Successully started webdriver!
[INFO][2] Video successfully loaded!
`
Chrome:
It seems that you only set http proxy in Chrome and not SSL proxy.
On my proxy servers I found out that HTTP isn't working only SSL is working.
Is there a way to set also the SSL proxy in Chrome?

```
python3 main.py -dr chrome -u https://www.youtube.com/watch?v=zUKnk4F0D5k -t 2 -p proxy.txt 
[INFO][0] 25 proxies successfully loaded!
[INFO][1] Connecting to 62.210.85.29:1050
[INFO][1] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
[INFO][1] Successully started webdriver!
[WARNING][1] Dead proxy eliminated!
[INFO][1] Connecting to 62.210.85.29:1049
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36
[INFO][2] Connecting to 62.210.85.29:1048
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36
[INFO][1] Successully started webdriver!
[INFO][2] Successully started webdriver!
[WARNING][1] Dead proxy eliminated!
[INFO][1] Connecting to 62.210.85.29:1047
[INFO][1] Setting user agent to Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7; ja-jp) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27
[WARNING][2] Dead proxy eliminated!
[INFO][2] Connecting to 62.210.85.29:1046
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko
[INFO][1] Successully started webdriver!
[INFO][2] Successully started webdriver!
[WARNING][1] Dead proxy eliminated!
[INFO][1] Connecting to 62.210.85.29:1045
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1623.0 Safari/537.36
[WARNING][2] Dead proxy eliminated!
```

**Comment by DeBos99** [comment]
Thanks for all informations. I'm working on the problem, but I don't know when it will be fixed.
As you can see in the logs, your proxies all marked as dead proxies which means that website is not loaded correctly. I will take a look at this issue after fixing the first one.

**Comment by DeBos99** [comment]
I fixed firefox proxies, so now IP is changed. Chrome is not changing IP for unknown reason, but it will be fixed soon.
