### ISSUE TITLE
[BUG] UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by StephanTimmers** [DeBos99/ytviewer#22]
**Description**
When I try to run this command I get this error:

**Command**
MacBook-Pro:ytviewer stephantimmers$ python main.py --url https://mixer.com/Nash2Stoned
100 proxies successfully loaded!
85.175.226.106:41175
Traceback (most recent call last):
  File "main.py", line 81, in bot
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

**Logs**
See above.

**Software**
OS: Mac
Python version: 2.7.10
WebDriver: Chrome

**Comment by DeBos99** [comment]
The is YouTube viewbot, not mixer view bot.
