### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by pimboli** [DeBos99/ytviewer#23]
**Description**
Crash after some time

**Command**
`python3 main.py -dr chrome -u https://www.youtube.com/watch?v=E89uLsHrN0g -t 5`

**Logs**
`[INFO][0] 100 proxies successfully loaded!
[INFO][1] Connecting to 95.165.244.122:58162
[INFO][1] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
[INFO][1] Successully started webdriver!
[INFO][2] Connecting to 182.16.162.89:32247
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.2 Safari/537.36
[INFO][2] Successully started webdriver!
[INFO][3] Connecting to 45.228.96.34:44206
[INFO][3] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
[INFO][3] Successully started webdriver!
[INFO][4] Connecting to 36.67.139.27:50466
[INFO][4] Setting user agent to Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36
[INFO][4] Successully started webdriver!
[INFO][5] Connecting to 125.26.7.249:43492
[INFO][5] Setting user agent to Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
[INFO][5] Successully started webdriver!
[WARNING][4] Dead proxy eliminated!
[INFO][4] Connecting to 169.239.46.92:8080
[INFO][4] Setting user agent to Mozilla/5.0 (X11; CrOS i686 3912.101.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36
[INFO][4] Successully started webdriver!
[INFO][1] Video successfully loaded!
[INFO][2] Video successfully loaded!
[WARNING][4] Dead proxy eliminated!
[INFO][4] Connecting to 197.255.152.43:55943
[INFO][4] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36
[INFO][4] Successully started webdriver!
[INFO][4] Video successfully loaded!
Traceback (most recent call last):
  File "main.py", line 92, in bot
    mute_button=driver.find_element_by_class_name('ytp-mute-button')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"ytp-mute-button"}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.13.5 x86_64)
`

**Software**
OS: mac
Python version: 3
WebDriver:

**Comment by DeBos99** [comment]
Fixed.
