### ISSUE TITLE
[FEATURE] Add donate button

### ISSUE THREAD

**Issue by pimboli** [DeBos99/ytviewer#24]
**Description**
Please add donate button to github  ytviewer page. :)
I would like to donate you for your work and your help.

**Requirements**
Clearly describe what requirements your feature has if any.

**Code**
You can include valid python code or pseudocode if you want to help me in adding your feature.

**Comment by DeBos99** [comment]
Thanks, I will add when I will have time.

**Comment by DeBos99** [comment]
I added donation button.
