### ISSUE TITLE
[QUESTION] Can we add Referrer?

### ISSUE THREAD

**Issue by ak0der1** [DeBos99/ytviewer#26]
As we are using Selenium, There is no official way to add referrer. but this guy tried something 4 years back, may be it still works.
https://github.com/j-bennet/selenium-referer
Can we test using it?

**Comment by DeBos99** [comment]
I'm not sure if this ever worked, but if so it was for firefox only I think.
There is other option to spoof referer.
I will take this video as example: https://www.youtube.com/watch?v=kJQP7kiw5Fk
It's id is `kJQP7kiw5Fk`.
If we will search for it on YouTube, first result is this video, so we have YouTube referer.
If we will search for `site:youtube.com kJQP7kiw5Fk` in google, we have Google referer.
Its possible to implement, but then one view needs 2 requests (one to google/youtube, second to video), so I have to find better proxies.
