### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'user_agent'

### ISSUE THREAD

**Issue by blitzwilli** [DeBos99/ytviewer#28]
Traceback (most recent call last):
  File "C:\Python37-32\ytviewer-master\main.py", line 11, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

**Comment by DeBos99** [comment]
Please run `pip install user_agent`.

**Comment by blitzwilli** [comment]
c:\Python37-32\ytviewer-master>pip install -U user_agent
Requirement already up-to-date: user_agent in c:\python37-32\lib\site-packages (0.1.9)
Requirement already satisfied, skipping upgrade: six in c:\python37-32\lib\site-packages (from user_agent) (1.12.0)

c:\Python37-32\ytviewer-master>main.py --url https://www.twitch.tv/BuffDarknessqr --duration 600
Traceback (most recent call last):
  File "C:\Python37-32\ytviewer-master\main.py", line 11, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

c:\Python37-32\ytviewer-master>

**Comment by DeBos99** [comment]
This is youtube views bot, not twitch.

**Comment by blitzwilli** [comment]
I saw a www.twitch.tv URL in your Youtube
https://www.youtube.com/watch?v=Sd3UKs7cDaY

**Comment by DeBos99** [comment]
This is not my video.
I'm helping only with the issues related to correct use of my software.
