### ISSUE TITLE
[BUG] WebDriverException: Message: setWindowRect [FIREFOX]

### ISSUE THREAD

**Issue by marko900** [DeBos99/ytviewer#29]
When I run bot have this error:

[INFO][2] Successully started webdriver!
Traceback (most recent call last):
  File "/home/pi/ytviewer/main.py", line 82, in bot
    driver.set_window_size(320,570)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1182, in set_window_rect
    "height": height})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: setWindowRect

**Software**
OS: Raspberry PI 3B+
Python version:Python 2.7.13 
WebDriver: This same after installation version.

When I remove this line: 
driver.set_window_size(320,570)

Bot works good, but when not remove this error appears

**Comment by DeBos99** [comment]
Please tell me what OS do you have.

**Comment by marko900** [comment]
OS? Operating system my Raspberry PI?
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

**Comment by DeBos99** [comment]
OS is Operating System. Do you have Raspbian installed or Kali Linux?

**Comment by marko900** [comment]
Standard systen Raspbian. I even not know that KaliLinux is also on Raspberry.

**Comment by DeBos99** [comment]
Did you download ARM version of geckodriver?

**Comment by marko900** [comment]
Do you mean it?
-> https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz

**Comment by DeBos99** [comment]
Yes, you can use these commands if you want:
```
sudo apt install iceweasel -y
wget "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz"
tar -xzf gecko*
sudo mv geckodriver /usr/bin
```

**Comment by marko900** [comment]
I have already installed several times and it did not help. Everything works fine without a line: driver.set_window_size(320,570) for me.

**Comment by DeBos99** [comment]
Ok, for now you have to keep this line deleted. When I will have time I will take a look at this bug.

**Comment by DeBos99** [comment]
Can you give me the command that you used to run the bot and tell me if you have lite version of Raspbian or normal?
