### ISSUE TITLE
Suggestion :D 

### ISSUE THREAD

**Issue by Tenx22** [DeBos99/ytviewer#3]
Add option to change the quality of video to 144p, this can help to load video faster with proxies, I guess.

**Comment by DeBos99** [comment]
Thanks for idea @Tenx22, I will take a look at it.

**Comment by apekoff** [comment]
Hi, now youtube auto set resolution by network speed and device resolution.  i think needed resize window for this ex.
```
# Resize the window to the screen width/height
driver.set_window_size(320, 570)
```

2years ago needed only get param in url ex. 
Code for 1440: vq=hd1440
Code for 1080: vq=hd1080
Code for 720: vq=hd720
Code for 480p: vq=large
Code for 360p: vq=medium
Code for 240p: vq=small

I test it, but this not worked now. I think need resize window resolution for selenium. Probably if proxy too slow - youtube automaticaly set low resolution.

**Comment by Tenx22** [comment]
what do you think about coding something complex, I can share you details about how is this going to work also for yt views. do you want to speak on discord or skype ?

**Comment by DeBos99** [comment]
Compared to my other projects its already complex, but we can speak on discord: DeBos#3292 (I'm busy, so only text chat if its not the problem).
