### ISSUE TITLE
Can't run de ytviewer[BUG]

### ISSUE THREAD

**Issue by y306841nwytg** [DeBos99/ytviewer#32]
This gets spammed in the console:
[INFO][13] Quitting webdriver!
[ERROR][13] Error quitting webdriver!
[INFO][13] Connecting to 105.27.143.190:54970
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
[INFO][1] Quitting webdriver!
[ERROR][1] Error quitting webdriver!
[INFO][1] Connecting to 118.78.196.145:8118
[INFO][1] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2922.34 Safari/537.36
[INFO][15] Quitting webdriver!
[ERROR][15] Error quitting webdriver!
[INFO][15] Connecting to 156.239.18.157:6604
[INFO][15] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Win64; x64; Trident/5.0)
[INFO][2] Quitting webdriver!
[ERROR][2] Error quitting webdriver!
[INFO][10] Quitting webdriver!

After running python main.py -u <yt url>
Python 2.7.16
Ubuntu 19.04

Any clue how to fix this?
I tried running all possible installations. (So option 1-1, 1-2, 2-1, 2-2)

**Comment by DeBos99** [comment]
You did not give the url so the bot is not working.

**Comment by y331625nwytg** [comment]
@DeBos99 can't react to my original account apparently the email verification failed.
I did python main.py -u <a valid youtube url>
For example: sudo python main.py -u https://www.youtube.com/watch?v=S55R9MA313c
And I get that spam in the console. Any idea what I can do to fix this?

**Comment by DeBos99** [comment]
I will add debug mode to the bot today, so you will be able to give me actual error message. I will let you know when I will update the bot.

**Comment by y331625nwytg** [comment]
Thanks a lot @DeBos99

**Comment by DeBos99** [comment]
I updated the bot. Please download the update by executing `git pull` command in `ytviewer` directory and tell me if you got any error messages. If yes, please send them here.

**Comment by y353220nwytg** [comment]
Thanks for the update @DeBos99 
Unfortunately I get this spammed:
INFO][6] Quitting webdriver!
[INFO][13] Connecting to 207.148.123.115:31330
[ERROR][6] Error quitting webdriver!
[ERROR][8] Unknown error occured!
[INFO][12] Quitting webdriver!
[ERROR][6] Unknown error occured!
[ERROR][12] Error quitting webdriver!
[INFO][5] Setting user agent to Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.3; WOW64; Trident/4.0)
[INFO][4] Setting user agent to Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2960.36 Safari/537.36
[ERROR][12] Unknown error occured!
[INFO][8] Connecting to 121.40.138.161:8000
[INFO][6] Connecting to 114.134.186.25:52071
[INFO][15] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2692.5 Safari/537.36
[INFO][12] Connecting to 95.134.195.78:43629
[INFO][9] Quitting webdriver!
[ERROR][9] Error quitting webdriver!
[INFO][2] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 10.0; Trident/5.0)
[INFO][3] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][4] Quitting webdriver!
[ERROR][9] Unknown error occured!
[INFO][7] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
[ERROR][4] Error quitting webdriver!
[ERROR][4] Unknown error occured!
[INFO][1] Quitting webdriver!
[INFO][9] Connecting to 192.117.146.110:80
[INFO][14] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2788.16 Safari/537.36
[ERROR][1] Error quitting webdriver!
[INFO][4] Connecting to 101.51.106.70:37769
[INFO][15] Quitting webdriver!
[ERROR][15] Error quitting webdriver!
[ERROR][1] Unknown error occured!
[ERROR][15] Unknown error occured!
[INFO][2] Quitting webdriver!
[INFO][10] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2868.23 Safari/537.36

I cant even stop the task using ctrl + c anymore haha!

**Comment by DeBos99** [comment]
Sorry, my bad. Add `-D` to the command.

**Comment by y353220nwytg** [comment]
No problem!
Got this output:
[INFO][0] 792 proxies successfully loaded!
[INFO][1] Connecting to 36.40.81.187:1080
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2917.9 Safari/537.36
[INFO][2] Connecting to 35.202.91.97:80
[INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][3] Connecting to 179.124.19.9:45173
[INFO][4] Connecting to 179.127.242.39:50121
[INFO][3] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
[INFO][4] Setting user agent to Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2683.28 Safari/537.36
[INFO][5] Connecting to 52.79.128.193:80
[INFO][6] Connecting to 168.205.251.130:53281
[INFO][7] Connecting to 37.187.149.234:1080
[INFO][8] Connecting to 118.174.220.58:60547
[INFO][5] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][7] Setting user agent to Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2847.33 Safari/537.36
[INFO][9] Connecting to 176.31.69.178:1080
[INFO][8] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][10] Connecting to 46.188.109.21:45952
[INFO][6] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2761.99 Safari/537.36
[INFO][9] Setting user agent to Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko
[INFO][10] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2796.19 Safari/537.36
[INFO][11] Connecting to 180.107.73.137:8060
[INFO][11] Setting user agent to Mozilla/5.0 (Windows NT 5.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][12] Connecting to 87.255.18.71:48376
[INFO][12] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][13] Connecting to 129.205.137.205:35076
[INFO][14] Connecting to 115.199.191.180:8118
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 5.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2822.24 Safari/537.36
[INFO][15] Connecting to 119.180.180.54:8060
[INFO][14] Setting user agent to Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
[INFO][15] Setting user agent to Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2710.21 Safari/537.36
[INFO][1] Quitting webdriver!
[INFO][4] Quitting webdriver!
[INFO][1] Connecting to 122.193.244.105:9999
Traceback (most recent call last):
  File "main.py", line 124, in bot
    try:driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by y353220nwytg** [comment]
By the way, I was wondering if you perhaps had a list of youtube accounts or if you know a fast way of making them. I usually get the problem that I need to use my phone number. Pretty offtopic woops

**Comment by DeBos99** [comment]
I made another update and problem should be gone.
I'm not interested in making many youtube accounts, but probably you could bypass phone number verification by creating the account after hard reset of the phone. I'm not sure if that still works, but this is method I used couple of months ago.

**Comment by y353220nwytg** [comment]
Thanks for that information! I'll try it out.
I now get this:
[INFO][0] 792 proxies successfully loaded!
[INFO][1] Connecting to 217.23.69.146:8080
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2730.21 Safari/537.36
[INFO][2] Connecting to 203.124.47.98:63141
[INFO][3] Connecting to 112.87.69.95:9999
[INFO][2] Setting user agent to Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Win64; x64; Trident/6.0)
[INFO][4] Connecting to 112.35.56.134:80
[INFO][4] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][3] Setting user agent to Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.1; WOW64; Trident/6.0)
[INFO][5] Connecting to 77.48.137.65:55082
[INFO][5] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2756.0 Safari/537.36
[INFO][6] Connecting to 95.80.252.189:52371
[INFO][7] Connecting to 217.27.41.138:44313
[INFO][8] Connecting to 13.233.9.54:80
[INFO][8] Setting user agent to Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2862.14 Safari/537.36
[INFO][9] Connecting to 105.29.85.19:38755
[INFO][6] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][11] Connecting to 46.101.1.221:80
[INFO][11] Setting user agent to Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][10] Connecting to 99.80.5.27:80
[INFO][9] Setting user agent to Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
[INFO][7] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2782.76 Safari/537.36
[INFO][12] Connecting to 217.182.51.225:1080
[INFO][12] Setting user agent to Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][10] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][13] Connecting to 176.235.170.182:56024
[INFO][14] Connecting to 114.113.220.149:80
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
[INFO][14] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2852.33 Safari/537.36
[INFO][15] Connecting to 139.99.219.132:80
[INFO][15] Setting user agent to Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2931.45 Safari/537.36
[INFO][12] Quitting webdriver!
[INFO][12] Connecting to 186.250.119.155:34377
Traceback (most recent call last):
  File "main.py", line 127, in bot
    for pid in pids:
UnboundLocalError: local variable 'pids' referenced before assignment

**Comment by DeBos99** [comment]
I made next update. Should work now.

**Comment by y353220nwytg** [comment]
@DeBos99 thanks!
Next error, sorry for bothering you so much.
[INFO][0] 792 proxies successfully loaded!
[INFO][1] Connecting to 78.107.239.115:58576
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2929.78 Safari/537.36
[INFO][2] Connecting to 157.230.56.112:8118
[INFO][3] Connecting to 176.123.164.240:58488
[INFO][2] Setting user agent to Mozilla/5.0 (X11; Linux i686; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][4] Connecting to 189.51.98.118:48704
[INFO][5] Connecting to 178.32.43.74:80
[INFO][3] Setting user agent to Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/4.0)
[INFO][5] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][4] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2649.77 Safari/537.36
[INFO][6] Connecting to 185.124.86.11:3128
[INFO][7] Connecting to 108.61.186.207:8080
[INFO][8] Connecting to 27.11.129.194:8118
[INFO][7] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Win64; x64; Trident/5.0)
[INFO][10] Connecting to 87.97.155.156:41312
[INFO][9] Connecting to 190.12.95.170:47754
[INFO][11] Connecting to 80.240.25.63:1080
[INFO][10] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
[INFO][8] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2703.67 Safari/537.36
[INFO][11] Setting user agent to Mozilla/5.0 (Windows NT 6.3; rv:50.0) Gecko/20100101 Firefox/50.0
[INFO][12] Connecting to 91.210.178.161:8080
[INFO][12] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; WOW64; Trident/5.0)
[INFO][9] Setting user agent to Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2841.57 Safari/537.36
[INFO][13] Connecting to 45.115.175.20:44448
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2850.97 Safari/537.36
[INFO][14] Connecting to 134.119.207.14:1080
[INFO][6] Setting user agent to Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko
[INFO][14] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2847.41 Safari/537.36
[INFO][15] Connecting to 120.210.219.101:80
[INFO][15] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2801.92 Safari/537.36
[INFO][13] Quitting webdriver!
[INFO][1] Quitting webdriver!
[INFO][9] Quitting webdriver!
[INFO][2] Quitting webdriver!
[INFO][3] Quitting webdriver!
[INFO][15] Quitting webdriver!
[INFO][14] Quitting webdriver!
[INFO][13] Connecting to 54.200.51.226:80
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Traceback (most recent call last):
  File "main.py", line 69, in bot
    driver=webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by DeBos99** [comment]
You are not bothering me, you are helping me fix the bot. The error says that you don't have driver in PATH. Did you get any errors when you were running the installer? Are you running bot as a normal user, not root? Could you give me output of `echo $PATH`?

**Comment by y356342nwytg** [comment]
Great to hear that! @DeBos99 
I don't think I've seen any errors during installation. I did install like all possibilities hehe.
I use sudo python main.py -u https://www.youtube.com/watch?v=aESwTpK3_v8 -D
response of echo: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by DeBos99** [comment]
Why are you using `sudo python main.py -u` instead of `python main.py -u`? This is not supported in my bot and this is why are you getting errors now.

**Comment by y356342nwytg** [comment]
I triedwithout sudo this time @DeBos99 : python main.py -u https://www.youtube.com/watch?v=aESwTpK3_v8 -D
And got

[INFO][0] 792 proxies successfully loaded!
[INFO][1] Connecting to 185.124.86.10:3128
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0
[INFO][2] Connecting to 3.82.116.153:3128
[INFO][2] Setting user agent to Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2797.45 Safari/537.36
[INFO][3] Connecting to 118.174.220.130:41419
[INFO][4] Connecting to 31.27.15.216:80
[INFO][4] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][5] Connecting to 169.57.1.84:80
[INFO][3] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
[INFO][6] Connecting to 47.244.55.164:3128
[INFO][5] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][6] Setting user agent to Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.3; WOW64; Trident/4.0)
[INFO][7] Connecting to 73.170.69.211:443
[INFO][7] Setting user agent to Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; Win64; x64; Trident/6.0)
[INFO][8] Connecting to 160.19.245.59:43983
[INFO][9] Connecting to 203.76.101.18:36761
[INFO][8] Setting user agent to Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0
[INFO][10] Connecting to 197.216.2.12:8080
[INFO][9] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
[INFO][11] Connecting to 112.35.56.134:80
[INFO][11] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][12] Connecting to 92.255.205.227:30359
[INFO][12] Setting user agent to Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko
[INFO][13] Connecting to 198.27.67.35:3128
[INFO][10] Setting user agent to Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2658.63 Safari/537.36
[INFO][14] Connecting to 103.79.74.1:53879
[INFO][14] Setting user agent to Mozilla/5.0 (Windows NT 10.0; Win64; x64; Trident/7.0; rv:11.0) like Gecko
[INFO][15] Connecting to 91.210.178.161:8080
[INFO][15] Setting user agent to Mozilla/5.0 (Windows NT 5.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0
[INFO][13] Setting user agent to Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2903.76 Safari/537.36
[INFO][2] Quitting webdriver!
[INFO][4] Quitting webdriver!
[INFO][6] Quitting webdriver!
[INFO][1] Quitting webdriver!
[INFO][2] Connecting to 125.25.45.7:54721
[INFO][10] Quitting webdriver!
Traceback (most recent call last):
  File "main.py", line 69, in bot
    driver=webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by DeBos99** [comment]
Can you give me output of `ls -l /usr/bin/*driver*`?

**Comment by y357037nwytg** [comment]
ofcourse @DeBos99 
ls -l /usr/bin/*driver*
lrwxrwxrwx 1 root root      29 mei 31 00:03 /usr/bin/driverless -> ../lib/cups/driver/driverless
-rwxrwxr-x 1 2000 2000 8091065 jan 28 23:50 /usr/bin/geckodriver
-rwxr-xr-x 1 root root      95 jan  7 20:01 /usr/bin/install-printerdriver
-rwxr-xr-x 1 root root    8491 mrt 18 16:20 /usr/bin/ubuntu-drivers

**Comment by DeBos99** [comment]
Looks like you don't have `chromedriver` installed. Can you run `sudo apt install chromium -y` and give me output?

**Comment by y357037nwytg** [comment]
Interesting! When I use: 
python main.py -u https://www.youtube.com/watch?v=aESwTpK3_v8 -D --dr firefox

(so without sudo)

It opens up a lot of browsers of firefox but then I get an error 

INFO][2] Successully started webdriver!
[INFO][8] Successully started webdriver!
[INFO][7] Successully started webdriver!
[INFO][2] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][6] Successully started webdriver!
[INFO][5] Successully started webdriver!
[INFO][9] Successully started webdriver!
[INFO][1] Successully started webdriver!
[INFO][12] Successully started webdriver!
[INFO][11] Quitting webdriver!
[INFO][8] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][7] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][5] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][9] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][6] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][1] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][12] Opening https://www.youtube.com/watch?v=aESwTpK3_v8
[INFO][12] Quitting webdriver!
Traceback (most recent call last):
  File "main.py", line 95, in bot
    driver.get(url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//www.youtube.com/watch%3Fv%3DaESwTpK3_v8&c=UTF-8&f=regular&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.youtube.com.


[INFO][11] Connecting to 81.211.94.210:8080
[INFO][11] Setting user agent to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2788.82 Safari/537.36


And in one of the browsers which havent been closed I see 
Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.youtube.com.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.

**Comment by y357037nwytg** [comment]
Oh sorry @DeBos99 I now remember what didnt work.
I tried to install it but got:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu:i386 chromium-bsu

E: Package 'chromium' has no installation candidate

So I tried installing chromium-bsu

**Comment by DeBos99** [comment]
This error that you got for firefox will be fixed in the next update. I'm not sure what to do with your `chromedriver`. I will have to do little research and I will let you know if I will get something.

**Comment by y357037nwytg** [comment]
Thanks! I'm always open to try things to fix the problem with the chromedriver even if I can properly use the firefox one :)

**Comment by DeBos99** [comment]
I made next update and now at least firefox should work for you.

**Comment by draceman** [comment]
How do I access main.py on Mac ? Having issues .

**Comment by DeBos99** [comment]
What do you mean access `main.py`?

**Comment by draceman** [comment]
I’m going to try again with some
More detailed feed back. What’s the first few steps for setting this up. If you don’t mind.

**Comment by DeBos99** [comment]
You have everything explained here: https://github.com/DeBos99/ytviewer#linux--macos
If you are getting any errors or you have any questions let me know.
