### ISSUE TITLE
[FEATURE] Run the script with proxychains

### ISSUE THREAD

**Issue by xtacyyy** [DeBos99/ytviewer#34]
I just wanted to know if we can run this script with the help of a proxychain since the proxysite the bot fetches from is blocked in my country. Using a VPN and running the script gives me an error saying that the request has been timed out. 

Thank you!

**Comment by DeBos99** [comment]
I will think about adding some kind of 'guard', so the connection will look like: You -> Guard -> Driver+Proxy -> Host (YouTube). For now you should try using other VPN.

**Comment by xtacyyy** [comment]
I've tried a few good VPNs, it seems like the videos play manually but not when its running under the bot.

**Comment by edison1105** [comment]
I had the same problem too.The proxies are blocked in my country.I tried to use a VPN and running the program, always got timed out.I have no idea how to fix this.

**Comment by DeBos99** [comment]
Ok, so what is blocked? Proxies or site itself? What countries are you from?

**Comment by xtacyyy** [comment]
The site is blocked, it can fetch the proxies once it runs on a vpn but the requests get timed out. I'm from the UAE.

**Comment by 2cool4u567** [comment]
I cant even open the install.bat or the main.python please help

**Comment by 2cool4u567** [comment]
i open the install.at and t just closes

**Comment by DeBos99** [comment]
Tell me your OS and python version.

**Comment by 2cool4u567** [comment]
oh hi DeBoss! Python version 3.7 and whats OS

**Comment by DeBos99** [comment]
OS is Operating System e.g. Windows, Linux or Mac OS.

**Comment by 2cool4u567** [comment]
oh, windows

**Comment by 2cool4u567** [comment]
do you got discord?

**Comment by DeBos99** [comment]
Yes, you have my discord on my profile and also in `README.md` files in every repo.

**Comment by 2cool4u567** [comment]
MY discord is ElectroGames#1865

**Comment by 2cool4u567** [comment]
i added you.

**Comment by 2cool4u567** [comment]
quickly i gtg so accept pleaase

**Comment by edison1105** [comment]
> Ok, so what is blocked? Proxies or site itself? What countries are you from?

It fetch the proxies from the proxy site successfully ! When the webdriver open my youtube video url,chrome always got request time out.So the proxies are blocked. I am from China.

**Comment by 2cool4u567** [comment]
help! i cant open someone plz

**Comment by xtacyyy** [comment]
Any updates?

**Comment by DeBos99** [comment]
No.

**Comment by xtacyyy** [comment]
updates?

**Comment by DeBos99** [comment]
No. I'm working on 10 other bots. This feature is not priority.

**Comment by xtacyyy** [comment]
Please take your time, I will be waiting. Cheers.

**Comment by DeBos99** [comment]
If you would write to me on discord (DeBos#3292) you can actually help me with that update. It will be just easier to make any tests.

**Comment by xtacyyy** [comment]
Sure, I'll be on it

**Comment by DeBos99** [comment]
Send me a message if you will add me. I don't have possibility to check who from github adds me on discord.
