### ISSUE TITLE
[BUG] Watch & views dissapear

### ISSUE THREAD

**Issue by b102266urhen** [DeBos99/ytviewer#38]
**Description**
The views done by the viewbot and watch time dissapear after 1-2 days

**Command**
python main.py -u <proper working url> -dr firefox

**Logs**
Logs of executed command.

**Software**
OS: Ubuntu
WebDriver:FireFox

Everything works fine, I see a lot of browsers getting opened and the video gets watched.
The watchtime increases then it gets removed by youtube somehow after 1-2 days.
Do we need better proxies?

**Comment by DeBos99** [comment]
I'm working on the issue. YouTube is detecting in some way that views are fake.
