### ISSUE TITLE
[QUESTION] Regarding Selenium.

### ISSUE THREAD

**Issue by Souldiv** [DeBos99/ytviewer#39]
Is there a reason that you used selenium instead of pyppeteer other than the fact it can't spawn firefox browsers?

**Comment by DeBos99** [comment]
Selenium is multi-language, multi-platform and has bigger community support, so in most cases I'm not first person that have some issue.

**Comment by Souldiv** [comment]
No offense mate, just wanted to know since i working on a similar project just wanted to know if i could do it with pyppeteer or i was missing something. Thanks anyways.

**Comment by DeBos99** [comment]
I don't see any offense here, it was just a question, but anyway I think that if you are planning to stay with Python, you can try to do it with pyppeteer, but I want to make my project as cross-platform and cross-everything as possible, so everyone can use it.
