### ISSUE TITLE
Getting an error when i use the bot

### ISSUE THREAD

**Issue by M1k3L1m3** [DeBos99/ytviewer#4]
![Capture](https://user-images.githubusercontent.com/36614258/55995203-809bc080-5c79-11e9-8b21-a66c3912bccc.PNG)

**Comment by DeBos99** [comment]
Thanks for reporting the error. Try downloading geckodriver for ARM: https://github.com/mozilla/geckodriver/issues/728 and replace the old one.

**Comment by M1k3L1m3** [comment]
still getting the same error

**Comment by DeBos99** [comment]
I started working on this problem. Make sure that right geckodriver is in the PATH (e.g. /usr/bin folder) and that previous one is deleted from system and trash. Try restarting your Raspberry Pi before running bot again.
Can you tell me what Raspberry Pi do you have and what OS?

**Comment by DeBos99** [comment]
I reproduced your error on my Raspberry Pi 3B+ and this should fix error:
```
sudo apt install iceweasel -y
wget "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz"
tar -xzf gecko*
sudo mv geckodriver /usr/bin
```
Make sure that other geckodriver(s) (packed or not) are deleted from download directory.

**Comment by M1k3L1m3** [comment]
thanks so much! it works!

**Comment by DeBos99** [comment]
I'm glad it works. Enjoy the bot.

**Comment by M1k3L1m3** [comment]
im getting a new error now 
![image](https://user-images.githubusercontent.com/36614258/56080793-185cf400-5dcb-11e9-9750-128364ba1d68.png)

**Comment by DeBos99** [comment]
Tell me what command are you running.

**Comment by M1k3L1m3** [comment]
python main.py -t 150 -u https://www.youtube.com/watch?v=w29tjZEq5tE -d 120 -p ./proxies.txt -us default -dr firefox

**Comment by DeBos99** [comment]
First of all use less threads (`-t`), because every thread means new browser and as far as I know it is too much for Raspberry Pi.
Secondly, is `default` existing file?

**Comment by M1k3L1m3** [comment]
no default is not existing it just said that there is a default in help

**Comment by M1k3L1m3** [comment]
and how many threads should i use

**Comment by DeBos99** [comment]
From help: `Set the user agent for the driver to AGENT (default: randomly generated user agent)` and
`Set the path of the user agents list for the driver to PATH (default: randomly generated user agent)`, which in your case means: if `default` is a file, select random user agent from it. If not, use `default` (word "default") as an user agent. If you want randomly generated user agent you have to just delete this option from your command.
I think you should use around 5 threads. Raspberry Pi is weak computer compared to PCs and laptops so even 5 can be problem. Definitely not 150.

**Comment by M1k3L1m3** [comment]
ok

**Comment by M1k3L1m3** [comment]
and what kind of proxies should i use. Right now im useing sock 4

**Comment by DeBos99** [comment]
You have to use HTTPS proxies.

**Comment by M1k3L1m3** [comment]
ok

**Comment by M1k3L1m3** [comment]
ok heres my command **python main.py -t 5 -u https://www.youtube.com/watch?v=w29tjZEq5tE -d 120 -p ./proxies.txt -dr firefox**

but now im getting this 
![image](https://user-images.githubusercontent.com/36614258/56081174-f154f100-5dcf-11e9-909b-c2426fd7f84e.png)

**Comment by DeBos99** [comment]
I'm not sure, but it can be some issue with your proxies. Try removing `-p` option to get default proxies.

**Comment by M1k3L1m3** [comment]
i removed -p and still the same error

**Comment by DeBos99** [comment]
Tell me what is version of firefox that you have installed.
Run `firefox --version` or `iceweasel --version`.
