### ISSUE TITLE
[QUESTION] How you did the tests?

### ISSUE THREAD

**Issue by Napproche** [DeBos99/ytviewer#45]
Hi,
Thanks for the bot. It's great to see how much time and effort you put in there. That's simply is amazing.
I'd like to ask you how did you conduct your tests?
You mentioned in one of the comments, that you sent "way more than 150 views per day".
I'd like to know the answer to these questions.
1- How many views you sent per hour?
2- What's the maximum views you sent per video and got counted by YouTube and within how many days?
Thanks again for your valuable time and effort.

**Comment by DeBos99** [comment]
Firstly I was using bot on my own channel. Now I have people that are testing the bot for me.
When I was testing the bot I was sending around 500 views per hour. Maximum number of views, as well as number of views per hour depends on proxies and speed of your internet connection.
