### ISSUE TITLE
Crashes when user is root and driver is chrome

### ISSUE THREAD

**Issue by hulkpwngan** [DeBos99/ytviewer#46]
**Description**
The script crashes when executing as root with chrome driver.

**Logs**
Traceback (most recent call last):
  File "main.py", line 102, in bot
  File "main.py", line 102, in bot
    chrome.options.add_argument('--no-sandbox')
    chrome.options.add_argument('--no-sandbox')

**Software**
OS: Ubuntu 18.04
Python version:
WebDriver:

**Solution**
replace Line 102
```
                                if is_root():
                                        chrome.options.add_argument('--no-sandbox')
```
with
```
                                if is_root():
                                        chrome_options.add_argument('--no-sandbox')
```

**Comment by DeBos99** [comment]
Thanks. I didn't spot that. I will fix that in a minute.
