### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by markuznw** [DeBos99/ytviewer#51]
Hello and thank you for your work on this script!

Unfortunately it seems to get detected with a 100% ratio in my testing cases. I even tried changing language of the browser to english since my chrome installation uses a localized language

Views work, they go up and minutes watched go up but they get removed in 24-48 hours.

For monetization it works even differently, they go up like 2 dollars for a single day then it gets locked to 0 and at the end of the month even the first 2 dollars get removed.

Is there any option to try or something to setup or it's just detected? Or maybe needs private proxies cause public ones are blacklisted?
Using default script (latest git commit 26565f124dcffc98051cca4be3f067e4f57e6d80) and options without making any changes, just passing -s (notebook) and -u with videos that i change every 1-2 days.

I forgot to say it used to work for a few days back in June or so :D

Thanks in advance :)

**Comment by DeBos99** [comment]
The bot would probably work better with residential proxies and something that spoofs `referer` header.
First problem has to be sorted out by yourself as its not my only bot and I'm not able to provide paid proxies for everyone.
Second problem could be fixed if I would make proxy server that would add random `referer` header to every request that goes through. I don't know when I will do this as I don't have that much time and I also have other projects to work on, but I'm working on it.
