### ISSUE TITLE
[QUESTION] script doesn't work on macOS or ubuntu 16.04 server

### ISSUE THREAD

**Issue by akrv** [DeBos99/ytviewer#52]
Tried running the script in macos and ubuntu server 16.04
used geckodriver and the following command line  

`python main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H
`

the error was always the same. after fixing any possible installation issues.
do you think its still an installation issue?

```
[WARNING][1] WebDriverException
[INFO][1] Quitting webdriver!
[INFO][1] Connecting to xxx.IP.addr.here:80
[INFO][1] Setting user agent to Mozilla/5.0 (Android 4.4.1; Tablet; rv:48.0) Gecko/48.0 Firefox/48.0
```

**Comment by DeBos99** [comment]
Did you choose chrome during installation?

**Comment by akrv** [comment]
tried again on a cloud server.
with -H for headless.

it didnt ask me for any installation.
I did `pip install -r requirements.txt` and then 
`python main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H`

**Comment by DeBos99** [comment]
So thats the issue. You have to do everything as in installation instructions on GitHub, so just clone repo and bot will install everything. If you want to do manual install (you actually started) you have to do it fully i.e. install driver and put in correct directory too.

**Comment by akrv** [comment]
I uninstalled the packages after cd into dir using 
`pip uninstall -r requirements.txt`

now, it asked me for installation.

first try, I chose chrome. 
same error.

next try, after uninstall again, I chose firefox
same error

**Comment by DeBos99** [comment]
Send me output of:
```
chromium --version
~/.DeBos/drivers/chromedriver --version
firefox --version
~/.DeBos/drivers/geckodriver --version
```

**Comment by akrv** [comment]
alright, looked at the install logs:
` 99% [....................................................... ] 54149chmod: cannot access '/root/.DeBos/drivers/*driver': No such file or directory
`
looks like the installation never succeeded.

**Comment by akrv** [comment]
I read the installation script and looks like the unzip fails for directory access.
I did the installation manually.
now the driver is successful and the bot works.
thank you for the help.
