### ISSUE TITLE
UT bot viewer

### ISSUE THREAD

**Issue by vladankuzmanovic5** [DeBos99/ytviewer#54]
Hi DeBos99, could you send me 500.000 views to https://www.youtube.com/watch?v=bHeCO0r0hpw, i installed github on, i made cmd, but when i start to usage ...py it shows s. error, 
could you show me some example where and how to write usage line, or simply sen views to this yt. thanks. Best regards, V.

**Comment by DeBos99** [comment]
I can send you 500.000 views for $1500.
If you will stick to instructions on GitHub you shouldn't get any errors.
There is usage line and full documentation available.
