### ISSUE TITLE
[FEATURE] - Support Proxy authentication

### ISSUE THREAD

**Issue by jikamu** [DeBos99/ytviewer#58]
**Description**
Support Authentication for Proxy

**Requirements**
- Able to provide Username and password

**Code**
You can include valid python code or pseudocode if you want to help me in adding your feature.

**Comment by DeBos99** [comment]
I can try adding this feature, but I need proxies for testing which I don't have, so if you are interested in helping me, you can contact me on Discord: DeBos#3292.

**Comment by DeBos99** [comment]
I added support for proxy authentication. Format for these proxies is `username:password@host:port`

**Comment by Marcindzindzer** [comment]
Where ?
