### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by m1lw0rm** [DeBos99/ytviewer#62]
**Description**
How to run without error?

**Command**
python2.7 main.py
python main.py -h

**Logs**

```
raceback (most recent call last):
  File "main.py", line 4, in exit
    with locks[3]:
NameError: global name 'locks' is not defined
[INFO] Exitting with exit code 1
```

> and : chmod: cannot access '/root/.DeBos/drivers/*driver': No such file or directory

**Software**
OS: Ubuntu 16.4
Python version: python 2.7
WebDriver: chromedriver, geckodriver

**Comment by DeBos99** [comment]
Run:
```
sudo apt install python3 -y
echo alias python=python3 >> ~/.bashrc
```
Then close and open terminal and run:
```
python -m pip uninstall selenium --user
python main.py --help
```
If that doesn't work, give me output of:
```
python --version
chromium --version
firefox --version
ls ~/.DeBos/drivers
```

**Comment by m1lw0rm** [comment]
Worked with adding that from you!

```
sudo apt install python3 -y
echo alias python=python3 >> ~/.bashrc
```

**Then close and open terminal and run:**

```
python -m pip uninstall selenium --user
python main.py --help
```

**and need that :** 

> `apt-get install python3-pip`
