### ISSUE TITLE
[QUESTION] macOS Mojave Error :/

### ISSUE THREAD

**Issue by zaferlatif** [DeBos99/ytviewer#64]
Hi,

Run: python main.py -u https://www.youtube.com/******** --threads 30 but an error;

Traceback (most recent call last):
  File "main.py", line 4, in exit
    with locks[3]:
NameError: global name 'locks' is not defined
[INFO] Exitting with exit code 1

########## OR ##########

Run python3 main.py -u https://www.youtube.com/******** --threads 30 but an error;

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    from psutil import Process,NoSuchProcess
ModuleNotFoundError: No module named 'psutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 50, in <module>
    try:INSTALLED
NameError: name 'INSTALLED' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 87, in <module>
  File "<string>", line 49, in install
NameError: name 'files_link' is not defined
[INFO] Exitting with exit code 1
-----------------------------------------------------------------------

Where I might be doing wrong? Thanks.

**Comment by DeBos99** [comment]
I fixed the issue, so everything should work correctly in around 30 minutes from now.
