### ISSUE TITLE
[Error when run with Centos 7 ]

### ISSUE THREAD

**Issue by fadimanar** [DeBos99/ytviewer#66]
[root@instance-group-1-36r7 ~]# cd ytviewer
[root@instance-group-1-36r7 ytviewer]# python main.py -u https://www.youtube.com/watch?v=qi8DqsH7xnM -d -H
[INFO] Bot is not installed.
[INFO] Starting installation.
[INFO] Detected 64bit architecture
[INFO] Starting driver installation.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: wget in /root/.local/lib/python2.7/site-packages (3.2)
Select browser for webdriver:
1) Google Chrome
2) Mozilla Firefox
3) All
#? 1
[INFO] Downloading webdriver from: https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
 98% [.............................chmod: cannot access ‘/root/.DeBos/drivers/*driver’: No such file or directory
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: psutil in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (5.6.3)
Requirement already up-to-date: argparse in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.4.0)
Requirement already up-to-date: user_agent in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (0.1.9)
Requirement already up-to-date: selenium-wire in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.0.10)
Requirement already up-to-date: requests[security] in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.22.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/site-packages (from user_agent->-r requirements.txt (line 3)) (1.9.0)
Requirement already satisfied, skipping upgrade: selenium>=3.4.0 in /root/.local/lib/python2.7/site-packages (from selenium-wire->-r requirements.txt (line 4)) (3.141.0)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (1.25.6)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (2019.9.11)
Requirement already satisfied, skipping upgrade: cryptography>=1.3.4; extra == "security" in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (2.7)
Requirement already satisfied, skipping upgrade: pyOpenSSL>=0.14; extra == "security" in /root/.local/lib/python2.7/site-packages (from requests[security]->-r requirements.txt (line 5)) (19.0.0)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 5)) (1.1.6)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 5)) (1.0.1)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 5)) (1.12.3)
Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 5)) (1.0.16)
Requirement already satisfied, skipping upgrade: pycparser in /root/.local/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 5)) (2.19)
100% [..........................................................................] 5425800 / 5425800[INFO] Successfully installed YTViewer.
[INFO] Starting bot.
Traceback (most recent call last):
  File "main.py", line 4, in exit
    with locks[3]:
NameError: global name 'locks' is not defined
[INFO] Exitting with exit code 1
[root@instance-group-1-36r7 ytviewer]#

**Comment by DeBos99** [comment]
Run `python main.py --help` and see if error still persists.
If yes: Add me on Discord (DeBos#3292) cause I will need more informations then.
If no: Run `python main.py -u URL -t 1 -d -H` and see if error still persists.

**Comment by fadimanar** [comment]
Error still persists. run with python main.py --help 
and python main.py -u URL -t 1 -d -H

**Comment by DeBos99** [comment]
Are you able to add me on Discord?

**Comment by fadimanar** [comment]
Ok

**Comment by fadimanar** [comment]
Sent invite Ms.Dana
