### ISSUE TITLE
[BUG] NameError: global name 'locks' is not defined

### ISSUE THREAD

**Issue by martincol21** [DeBos99/ytviewer#67]
**Description**
Error:
pi@raspberrypi:~/ytviewer $ sudo python main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H -D firefox
[INFO] Bot is not installed.
[INFO] Starting installation.
[INFO] Detected 7lbit architecture
[INFO] Starting driver installation.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: wget in /root/.local/lib/python2.7/site-packages (3.2)
Select browser for webdriver:
[INFO] Downloading webdriver from: https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux7l.tar.gz
Traceback (most recent call last):
  File "main.py", line 4, in exit
    with locks[3]:
NameError: global name 'locks' is not defined
[INFO] Exitting with exit code 1

**Command**
sudo python main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H -D firefox

**Software**

Python version: 2.7

OSl: Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

I installed:
sudo apt install iceweasel -y
wget "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz"
tar -xzf gecko*
sudo mv geckodriver /usr/bin

**Comment by DeBos99** [comment]
Update Python to version 3 first of all.
