### ISSUE TITLE
This is work? Just to make a sure 

### ISSUE THREAD

**Issue by asu01928** [DeBos99/ytviewer#69]
Hi my analytical youtube is not increased and the views still the same
firefox
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/ytviewer# sudo python3 main.py -u https://youtu.be/xETsljyWhUU -s -D firefox -du 10 -d
[INFO] 672 proxies successfully loaded!                                                 [INFO][1] Connecting to 46.172.76.114:41562                                             [INFO][2] Connecting to 96.9.90.83:55944                                                [INFO][2] Setting user agent to Mozilla/5.0 (Windows NT 5.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2882.76 Safari/537.36
[INFO][6] Connecting to 178.213.0.207:35140                                             [INFO][8] Connecting to 190.7.113.51:80                                                 [INFO][8] Setting user agent to Mozilla/5.0 (Linux; Android 6.0; Micromax D320 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2836.96 Mobile Safari/537.36
[INFO][12] Connecting to 202.61.49.52:48298                                             [INFO][12] Setting user agent to Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; WOW64; Trident/4.0)                                                                         [INFO][3] Connecting to 91.200.166.200:3128
[INFO][3] Setting user agent to Mozilla/5.0 (Android 6.0.1; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0
[INFO][9] Connecting to 145.239.169.47:1080

**Comment by DeBos99** [comment]
Wait more time.
