### ISSUE TITLE
WebDriverException: Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by bonfix** [DeBos99/ytviewer#7]
I get the following error when using mozilla, on centos 7.

![2019-04-19 13_51_01-root@cityhyper_~_bots_ytviewer_ytviewer](https://user-images.githubusercontent.com/8567807/56421263-587c1500-62aa-11e9-90c3-bb8f85b61bc0.png)

**Comment by bonfix** [comment]
Also getting this error on Chrome

![2019-04-19 13_56_45-root@cityhyper_~_bots_ytviewer_ytviewer](https://user-images.githubusercontent.com/8567807/56421423-17383500-62ab-11e9-9481-6f81abefd31f.png)

**Comment by DeBos99** [comment]
Did you click anything before encountering this error?

**Comment by bonfix** [comment]
No, I'm using a remote server

**Comment by DeBos99** [comment]
Try adding `-t 1` to your command and run again.
Does your server have any desktop environment or you have only terminal?

**Comment by bonfix** [comment]
I only have a terminal.
Still gives an error for both:

![2019-04-19 14_32_19-root@cityhyper_~_bots_ytviewer_ytviewer](https://user-images.githubusercontent.com/8567807/56422442-0c33d380-62b0-11e9-91ae-c74d48462222.png)

**Comment by DeBos99** [comment]
Lack of desktop environment is the issue here. I will add support for PyVirtualDisplay as fast as possible.

**Comment by bonfix** [comment]
Ok, thanks!

**Comment by DeBos99** [comment]
Please run following commands in your terminal:
```
pip install pyvirtualdisplay
yum install -f xorg-x11-server-Xvfb
```
Then run `python` and send me screenshot of the output of:
```
from pyvirtualdisplay import Display
from selenium import webdriver

display=Display(visible=0, size=(1024, 768))
display.start()
browser=webdriver.Firefox()
```
Eventually you can try the same with chromedriver by replacing `webdriver.Firefox()` with `webdriver.Chrome()`.

**Comment by bonfix** [comment]
Output requested is here:

![1](https://user-images.githubusercontent.com/8567807/56460980-d4ae4f80-63b3-11e9-8d23-8fe01682d450.png)

**Comment by DeBos99** [comment]
Thanks, can you now try running only this commands in `python`:
```
from selenium import webdriver
browser=webdriver.Firefox()
```
and send me output?

**Comment by bonfix** [comment]
![2019-04-20 21_42_48-Window](https://user-images.githubusercontent.com/8567807/56461070-4e930880-63b5-11e9-9f25-00a8ab47e9f4.png)

**Comment by bonfix** [comment]
**The contents of geckodriver.log**

Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
1555786111045	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.YerkuAh6u4pT"
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Running without a11y support!
Error: no DISPLAY environment variable specified

**Comment by bonfix** [comment]
@DeBos99 It seems the solution is to simply start mozilla headless:
Added these lines

```
from selenium.webdriver.firefox.options import Options

options = Options()
![2019-04-20 22_00_57-Window](https://user-images.githubusercontent.com/8567807/56461233-db3ec600-63b7-11e9-91ad-a5baf67f5249.png)

options.headless = True
driver=webdriver.Firefox(options=options,firefox_profile=firefox_profile)
```

Seems to be working but gives the following error after a few mins

**Comment by DeBos99** [comment]
I don't know if the views will be still counted using headless mode. As far as I know `connection refused` is common error in headless mode. I will do the update next week. I will give you information here when I will do the update.

**Comment by DeBos99** [comment]
Added support for headless driver.
