### ISSUE TITLE
views youtube

### ISSUE THREAD

**Issue by wefdgfgfgfg** [DeBos99/ytviewer#8]
Hi, why can I do only 151-182 views youtube? on one video. The program works fine, but stops working after these views.

**Comment by DeBos99** [comment]
What means "stops working"? On software side or YouTube side?

**Comment by wefdgfgfgfg** [comment]
When the software is running, YouTube stops counting video after 150 views.                                                                                                           
You can add code to search for a video to play it? I assume that YouTube sees the logic of the requests.                                                                                                           
I know that there is no support for proxy with authorization                                                                                                           
Have you thought about how to solve this problem?

**Comment by DeBos99** [comment]
I checked bot myself for months before I published it on github. When do you see that 150 views? On video's analytics or video itself? For now I only thought about changing `Referer` header in request to fake traffic source.

**Comment by DeBos99** [comment]
I can think about adding support for proxies with authorization, but for now I'm thinking about moving project to ruby (same repo, just other code). I saw that bot doesn't kill some windows sometimes, which can cause some problems on some machines.

**Comment by wefdgfgfgfg** [comment]
does not change to video. when watching a single video, within two hours, after 150 views - the video is "banned". statistics no longer changes for this video even from other devices. analytics shows views.

**Comment by wefdgfgfgfg** [comment]
How did you do the tests? What were the settings, what were the results?

**Comment by DeBos99** [comment]
I had YouTube channel around year ago and I got to like 30 subs and 2k views/video (around 10 videos), but after some time I decided that YouTube is not what I want to do and I published the bot. If views are showing in analytics everything is fine. They should update in like 2 days depending on channel. It's YouTube's 'normal' behaviour when it sees e.g. 500 views on channel with average 10 per video and I can do nothing with that.

**Comment by wefdgfgfgfg** [comment]
If you want to add a referrer field, Google’s bot will most likely check it for a link

**Comment by DeBos99** [comment]
What do you mean by that? Do you think that adding this header will not improve bot in any way? Do you have any suggestions what could I add/change to make bot better?

**Comment by wefdgfgfgfg** [comment]
Google indexes all traffic source links. 
Perhaps referral links will come from closed social networks where there is no Google indexing 
one video can score > 1M views 
Are you sure that Google still somehow determines the uniqueness of the visitor through JS? 
Must be the logic of browser behavior. This logic is there! 
It is necessary to ease the load on the CPU when opening browsers 
Need to use a proxy with authorization! 
If possible, you need to block incoming UDP packets, this will ease the load on the network. 
On technical issues and logic I can write in private

**Comment by wefdgfgfgfg** [comment]
I asked my friends. They have a bot network, they have no such problems, so Google sees the uniqueness of the machine!                                                                                                           
You need to watch the scripts on the video through the debugger. Determines the uniqueness of the machine

**Comment by DeBos99** [comment]
You can't determine uniqueness of the machine in any way.
Cookies? I can clear history.
IP Address? I can use proxy.
MAC Address? Probably can't get it, but I can change it anyway.

**Comment by wefdgfgfgfg** [comment]
I clear the history, and change the proxy - it does not help, maybe this is MAC Address                                                                                                           
Google accurately determines the uniqueness of the machine                                                                                                           
If with 1000 devices can spin 1000 views, but this program can not                                                                                                           
Please look through the debugger scripts that work out on YouTube.                                                                                                           
Try adding referrals to the code and MAC Address

**Comment by DeBos99** [comment]
Like I said I checked bot myself. As far as I know you are not able to tell that this machine is the same machine using PHP or JavaScript in this case because every proxy gets own 'clear' browser. Only things that is the same is lack of `Referer` header, but I'm working on it and browser version.

**Comment by wefdgfgfgfg** [comment]
https://stackoverflow.com/questions/3385/mac-addresses-in-javascript 
I did the tests. per day from one machine you can wind up 150 views, with your program you can wind up 150 views, I asked the guys to wind up views from 1000 computers and 1000 views in one go!                                                                                                           
the header of the referrer can only complement the logic of the program, but not solve the basic problem of the uniqueness of the user.

**Comment by wefdgfgfgfg** [comment]
https://github.com/beefproject/beef/wiki/Information-Gathering#browser-fingerprinting 
 Need to think about Browser fingerprinting

**Comment by wefdgfgfgfg** [comment]
https://github.com/CryptoCubik/browserprint
https://github.com/Valve/fingerprintjs

**Comment by wefdgfgfgfg** [comment]
I watched the YouTube code, they collect fingerprints, I found several base.js Vo=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a}; a.macros.SURVEY_LOCAL_TIME_EPOCH_S=b(function(){var c=new Date;return Math.round(c.valueOf()/1E3)+-60*c.getTimezoneOffset()});

**Comment by DeBos99** [comment]
I told you already that I tested bot myself and it was way more views than 150/day. It was before I added proxies, there was only user agent changed, so all views were from single IP address.
The `Referer` header will add little bit of 'fake user action', so it will improve the bot.
There is no something like `uniqueness of the user` here. Everything can be easily spoofed.
You can only check uniqueness by account, but views from people without account are counted too.
I'm already working on the problem.

**Comment by wefdgfgfgfg** [comment]
Internal analytics of the channel has views, but external views that move the video to the top are limited to 150-180 views. google collects fingerprints the user agent screen size color depth the timezone offse sessionStorage suppor localStorage support

**Comment by DeBos99** [comment]
I was getting views after around day after I saw them in analytics.
User agent is nothing unique, same story with screen size and timezone.
