### ISSUE TITLE
It doesn't work very well and fast exit.

### ISSUE THREAD

**Issue by MrAlfo** [DeBos99/ytviewer#9]
First of all, thank you very much for your work. But even though I've added a proxy from outside, I get an error after 20 runs. And watching certainly does not increase. Where do I make the mistake? It doesn't work properly. Can u help me?

**Comment by DeBos99** [comment]
Please give me more details on that. I need error message from bot to help you. Can you tell me what do you mean by 'watching certainly does not increase'? Did you check the analytics? YouTube has some kind of bug itself and doesn't update 'analytics views' instantly.

**Comment by MrAlfo** [comment]
![image](https://user-images.githubusercontent.com/26857716/57011795-1937b780-6c0c-11e9-9114-6a6caffe4d79.png)

Look at this screen DeBoss99. Of course, I just started to python. Im beginner. As I said, it doesn't continue after 10 proxies. Can u help me?

**Comment by MrAlfo** [comment]
Just look at the right-side on the screenshot.

**Comment by MrAlfo** [comment]
Just look at the rightside on the screenshots.

**Comment by DeBos99** [comment]
As far as I know its problem with selenium itself not with the bot. I suggest making sure that you have:
- Up to date browser
- Up to date driver
- Firewall configured correctly (you are not blocking anything or its turned off)
